# Generated by Django 5.1.3 on 2024-11-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songapi', '0002_alter_album_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_year',
            field=models.IntegerField(default=2000),
        ),
    ]
