# Generated by Django 5.1.3 on 2024-11-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songapi', '0003_alter_album_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
