# Generated by Django 5.1.3 on 2024-11-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songapi', '0004_alter_album_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album_art_path',
            field=models.ImageField(upload_to='song_album_art/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_path',
            field=models.FileField(upload_to='song/'),
        ),
    ]
